#!/usr/bin/env python3
"""Pack a built spatch bundle into a platform wheel.

    ./make_wheel.py --bundle dist/bundle-x86_64

The wheel is written as a zip directly rather than through a build backend for
one reason: the executable bit on ``spatch``. Setuptools does not reliably
preserve mode bits on package data, and a wheel whose binary unpacks as 0644 is
broken in a way that only shows up at run time.
"""

import argparse
import base64
import csv
import hashlib
import io
import stat
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
DISTRIBUTION = 'cvehound_spatch'
PACKAGE = 'cvehound_spatch'
SUMMARY = 'Prebuilt Coccinelle spatch binary, tailored for CVEhound'

# uname machine -> the manylinux platform tag the build image produces
PLATFORM_TAGS = {
    'x86_64': 'manylinux_2_28_x86_64',
    'aarch64': 'manylinux_2_28_aarch64',
}

# Deterministic zip timestamp: the wheel content is a function of the bundle,
# not of when it was packed.
ZIP_DATE = (1980, 1, 1, 0, 0, 0)


def parse_build_info(path: Path) -> dict[str, str]:
    info = {}
    for line in path.read_text().splitlines():
        if ': ' in line:
            key, value = line.split(': ', 1)
            info[key.strip()] = value.strip()
    return info


def build_info_module(version: str, info: dict[str, str]) -> str:
    spatch_version = info.get('spatch_version', '')
    coccinelle_version = spatch_version.split()[2] if spatch_version else 'unknown'
    lines = [
        '"""Generated by make_wheel.py at pack time. Do not edit."""',
        '',
        f'__version__ = {version!r}',
        f'COCCINELLE_VERSION = {coccinelle_version!r}',
        f'COCCINELLE_COMMIT = {info.get("coccinelle_sha", "unknown")!r}',
        'BUILD_INFO = {',
    ]
    lines += [f'    {k!r}: {v!r},' for k, v in info.items()]
    lines += ['}', '']
    return '\n'.join(lines)


def metadata(version: str, readme: str) -> str:
    fields = [
        'Metadata-Version: 2.4',
        f'Name: {DISTRIBUTION.replace("_", "-")}',
        f'Version: {version}',
        f'Summary: {SUMMARY}',
        'Author: Denis Efremov',
        'Author-email: efremov@linux.com',
        'License-Expression: GPL-2.0-only',
        'License-File: LICENSE',
        'Project-URL: Homepage, https://github.com/evdenis/cvehound-spatch',
        'Project-URL: CVEhound, https://github.com/evdenis/cvehound',
        'Project-URL: Coccinelle, https://github.com/coccinelle/coccinelle',
        'Classifier: Development Status :: 4 - Beta',
        'Classifier: Intended Audience :: Developers',
        'Classifier: Operating System :: POSIX :: Linux',
        'Classifier: Programming Language :: Python :: 3',
        'Classifier: Topic :: Security',
        'Classifier: Topic :: Software Development :: Quality Assurance',
        'Requires-Python: >=3.9',
        'Description-Content-Type: text/markdown',
    ]
    return '\n'.join(fields) + '\n\n' + readme


def wheel_file(tag: str) -> str:
    return '\n'.join(
        [
            'Wheel-Version: 1.0',
            'Generator: make_wheel.py',
            'Root-Is-Purelib: false',
            f'Tag: {tag}',
            '',
        ]
    )


class WheelWriter:
    """Collects members, hashing each one for RECORD as it goes."""

    def __init__(self, path: Path) -> None:
        self._zip = zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED)
        self._record: list[tuple[str, str, int]] = []

    def add_bytes(self, name: str, data: bytes, mode: int = 0o644) -> None:
        info = zipfile.ZipInfo(name, date_time=ZIP_DATE)
        # Installers only honour the mode when the entry looks like it came
        # from a Unix zip: pip tests stat.S_ISREG on the high half, so the
        # regular-file bits have to be there or spatch installs as 0644.
        info.create_system = 3
        info.external_attr = (stat.S_IFREG | mode) << 16
        info.compress_type = zipfile.ZIP_DEFLATED
        self._zip.writestr(info, data)
        digest = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b'=').decode()
        self._record.append((name, f'sha256={digest}', len(data)))

    def add_text(self, name: str, text: str, mode: int = 0o644) -> None:
        self.add_bytes(name, text.encode(), mode)

    def add_file(self, name: str, source: Path, mode: int = 0o644) -> None:
        self.add_bytes(name, source.read_bytes(), mode)

    def close(self, record_name: str) -> None:
        buf = io.StringIO()
        writer = csv.writer(buf, lineterminator='\n')
        for row in self._record:
            writer.writerow(row)
        # RECORD cannot hash itself.
        writer.writerow((record_name, '', ''))
        info = zipfile.ZipInfo(record_name, date_time=ZIP_DATE)
        info.create_system = 3
        info.external_attr = (stat.S_IFREG | 0o644) << 16
        self._zip.writestr(info, buf.getvalue())
        self._zip.close()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--bundle', required=True, type=Path, help='directory built by build.sh')
    parser.add_argument('--plat', help='platform tag (default: from the bundle directory name)')
    parser.add_argument('--outdir', type=Path, default=HERE / 'dist')
    args = parser.parse_args()

    bundle: Path = args.bundle
    plat = args.plat
    if not plat:
        arch = bundle.name.rsplit('-', 1)[-1]
        plat = PLATFORM_TAGS.get(arch)
        if not plat:
            parser.error(f'cannot infer a platform tag from {bundle.name!r}; pass --plat')

    version = (HERE / 'VERSION').read_text().strip()
    info = parse_build_info(bundle / 'BUILD-INFO')
    readme = (HERE / 'README.md').read_text()

    tag = f'py3-none-{plat}'
    args.outdir.mkdir(parents=True, exist_ok=True)
    wheel_path = args.outdir / f'{DISTRIBUTION}-{version}-{tag}.whl'
    dist_info = f'{DISTRIBUTION}-{version}.dist-info'

    wheel = WheelWriter(wheel_path)
    for name in ('__init__.py', '__main__.py'):
        wheel.add_file(f'{PACKAGE}/{name}', HERE / 'src' / PACKAGE / name)
    wheel.add_text(f'{PACKAGE}/_build_info.py', build_info_module(version, info))
    wheel.add_file(f'{PACKAGE}/spatch', bundle / 'spatch', mode=0o755)
    for name in ('standard.h', 'standard.iso', 'BUILD-INFO'):
        wheel.add_file(f'{PACKAGE}/{name}', bundle / name)
    wheel.add_text(f'{dist_info}/METADATA', metadata(version, readme))
    wheel.add_text(f'{dist_info}/WHEEL', wheel_file(tag))
    wheel.add_file(f'{dist_info}/licenses/LICENSE', HERE / 'LICENSE')
    wheel.close(f'{dist_info}/RECORD')

    size = wheel_path.stat().st_size
    print(f'{wheel_path} ({size / 1e6:.1f} MB)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
